### ISSUE TITLE
Update readme to specify R version

### ISSUE THREAD

**Issue by jhawkey** [scwatts/vitek_export#1]
Hey Stephen,

Can we please update the readme to specify that if running this code on M3 you need to `module load R/4.1.0-mkl`? We've discovered that the cast_data.R script doesn't correctly map the greaterThan/Equals relationships (for some reason Equals values get a '>') using R v3.6.0 and older. No idea why but using v4.1.0 fixes the issue!

Thanks

**Comment by scwatts** [comment]
Closed by:

- #2
